#!/usr/bin/env ruby

require "aws-sdk"

METADATA_ENDPOINT = "http://169.254.169.254/latest/meta-data/instance-id"

ec2 = Aws::EC2::Client.new region: ENV["AWS_REGION"]
instance_id = Net::HTTP.get(URI.parse METADATA_ENDPOINT)

tag = ec2.describe_tags({filters: [{name: "resource-id", values: [instance_id]}]}).to_h[:tags]
  .find{|tag| tag[:key]== "Name"}

puts ec2.describe_instances(filters:[{ name: "tag:Name", values: [tag[:value]] }]).reservations
  .map(&:instances).flatten.map(&:private_ip_address).compact
