#!/usr/bin/env ruby

require "aws-sdk"
require "fileutils"

def error_exit msg
  STDERR.puts "[ERROR] #{msg}"
  exit 1
end

S3_DOTENV_PATH = "ec2_setting_files/dotenv"
LOCAL_DOTENV_PATH = "/home/deploy/.env"
BACKUP_DIR = "/home/deploy/dotenv_backups"

s3 = Aws::S3::Resource.new region: ENV["AWS_REGION"]
bucket = s3.bucket ENV["S3_BUCKET_NAME"]

begin
  bucket.object(S3_DOTENV_PATH).get(response_target: LOCAL_DOTENV_PATH)
rescue Aws::S3::Errors::NoSuchKey
  error_exit "#{S3_DOTENV_PATH} doesn't exist in your S3 bucket."
end
